"""Project-wide configuration and shared utilities.

Data layer roles (all tables live in a single SQLite file at DB_PATH):

  raw    — source data, append-only or full-replace per ingestion run
           flights_raw, stock_prices, earnings_calendar

  mart   — cleaned, deduplicated, research-ready tables
           earnings_calendar_master  ← canonical one-row-per-(ticker, fiscal_quarter)
           flights_monthly_features
           flights_quarterly_features
           earnings_event_features
           earnings_event_sequences

  output — model results and backtest outputs
           sde_summary, sde_paths
           factor_backtest_dataset, factor_ic_results
           factor_backtest_summary, ls_portfolio_returns
           sentiment_factors

  meta   — pipeline observability
           pipeline_run_log

All downstream research modules (feature_engineering, factor_backtest, agent)
must read from mart/output tables only — never directly from raw tables.
"""
from __future__ import annotations

import datetime
import os
import sqlite3
from pathlib import Path


ROOT_DIR   = Path(__file__).resolve().parent
DATA_DIR   = ROOT_DIR / "data"
DB_PATH    = DATA_DIR / "airline.db"
MODELS_DIR = ROOT_DIR / "models"
REPORTS_DIR = ROOT_DIR / "reports"
CHARTS_DIR  = REPORTS_DIR / "charts"

TARGET_TICKERS = ["AAL", "DAL", "UAL", "LUV", "JBLU", "ALK"]
TICKER_TO_CARRIER = {
    "AAL":  "AA",
    "DAL":  "DL",
    "UAL":  "UA",
    "LUV":  "WN",
    "JBLU": "B6",
    "ALK":  "AS",
}
CARRIER_TO_TICKER = {carrier: ticker for ticker, carrier in TICKER_TO_CARRIER.items()}


def ensure_directories() -> None:
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    MODELS_DIR.mkdir(parents=True, exist_ok=True)
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    CHARTS_DIR.mkdir(parents=True, exist_ok=True)


def load_dotenv(dotenv_path: Path | None = None) -> None:
    path = dotenv_path or ROOT_DIR / ".env"
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip("\"'"))


def log_pipeline_run(
    conn: sqlite3.Connection,
    run_id: str,
    module: str,
    status: str,
    output_table: str,
    row_count: int,
    sample_start: str,
    sample_end: str,
) -> None:
    """Write one metadata row to pipeline_run_log.

    Call once per module after writing its primary output table.
    run_id is generated by main.py at startup and passed via --run-id.
    """
    conn.execute(
        """
        CREATE TABLE IF NOT EXISTS pipeline_run_log (
            run_id       TEXT,
            run_ts       TEXT,
            module       TEXT,
            status       TEXT,
            output_table TEXT,
            row_count    INTEGER,
            sample_start TEXT,
            sample_end   TEXT
        )
        """
    )
    conn.execute(
        "INSERT INTO pipeline_run_log VALUES (?,?,?,?,?,?,?,?)",
        (
            run_id,
            datetime.datetime.utcnow().isoformat(),
            module,
            status,
            output_table,
            row_count,
            sample_start,
            sample_end,
        ),
    )
