"""
Pipeline Report Agent — powered by GPT-5.

Runs at the end of each pipeline execution. Reads all stage outputs,
and generates a structured Markdown report saved to
reports/run_YYYYMMDD_HHMMSS.md.
"""
from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Any, Dict, Optional

import openai

REPORTS_DIR: str = os.path.join(os.path.dirname(os.path.dirname(__file__)), "reports")
LAST_RUN_PATH: str = os.path.join(REPORTS_DIR, "_last_run_metrics.json")

_SYSTEM_PROMPT = """\
You are a quantitative research analyst. You will receive a JSON snapshot of a
pipeline run (training metrics, SDE backtest metrics, factor backtest results).

Generate a professional Markdown report with:
1. ## Executive Summary (3-5 bullets — key outcomes from the current run)
2. ## Training & SDE Metrics (table format)
3. ## Portfolio Performance (gross vs net Sharpe, win rate, regime breakdown)
4. ## Factor Analysis (IC table, factor correlation highlights)
5. ## Recommendations (2-4 actionable suggestions)
6. Footer: "Generated by QF5214 pipeline report agent — <timestamp>"

Be factual, concise, and analyze only the current run. Do not compare to prior runs.
"""


def _build_snapshot(
    bt: Optional[Dict[str, Any]],
    train_info: Optional[Dict[str, Any]],
    fund_result: Optional[Dict[str, Any]],
) -> Dict[str, Any]:
    snap: Dict[str, Any] = {"timestamp": datetime.now().isoformat()}

    if train_info:
        snap["training"] = {
            "n_train": train_info.get("n_train"),
            "sigma_train": train_info.get("sigma_train"),
            "sigma_oos": train_info.get("sigma_oos"),
            "best_iteration": train_info.get("best_iteration"),
        }

    if bt:
        snap["sde_backtest"] = {
            "mae": bt.get("mae"),
            "wmape": bt.get("wmape"),
            "rmse": bt.get("rmse"),
            "n_test": bt.get("n_test"),
            "from_cache": bt.get("from_cache"),
        }

    if fund_result and fund_result.get("n_quarters", 0) > 0:
        ic = fund_result.get("ic_by_factor", {})
        snap["portfolio"] = {
            "n_quarters": fund_result.get("n_quarters"),
            "cumulative_return_gross": fund_result.get("cumulative_return"),
            "cumulative_return_net": fund_result.get("cumulative_return_net"),
            "annualized_sharpe_gross": fund_result.get("annualized_sharpe"),
            "annualized_sharpe_net": fund_result.get("annualized_sharpe_net"),
            "sharpe_ci": [fund_result.get("sharpe_ci_lo"), fund_result.get("sharpe_ci_hi")],
            "win_rate": fund_result.get("win_rate"),
            "p_value_mean_return": fund_result.get("p_value"),
            "ic_by_factor": ic,
            "ic_pvalues": fund_result.get("ic_pvalues", {}),
            "regime_stats": {
                k: {m: round(v, 4) for m, v in vs.items()}
                for k, vs in (fund_result.get("regime_stats") or {}).items()
            },
        }

    return snap


def _save_last_run(snap: Dict[str, Any]) -> None:
    os.makedirs(REPORTS_DIR, exist_ok=True)
    with open(LAST_RUN_PATH, "w", encoding="utf-8") as f:
        json.dump(snap, f, indent=2, default=str)


def _ask_gpt(snap: Dict[str, Any], model: str, temperature: float) -> str:
    client = openai.OpenAI(
        api_key=os.environ.get("OPENAI_API_KEY"),
        base_url=os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1"),
    )
    resp = client.chat.completions.create(
        model=model,
        temperature=temperature,
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": json.dumps({"current_run": snap}, default=str)},
        ],
    )
    return resp.choices[0].message.content.strip()


def run_report(
    bt: Optional[Dict[str, Any]],
    train_info: Optional[Dict[str, Any]],
    fund_result: Optional[Dict[str, Any]],
    cfg: Dict[str, Any],
) -> None:
    agent_cfg = cfg.get("agents", {})
    model: str = agent_cfg.get("model", "gpt-5")
    temperature: float = float(agent_cfg.get("temperature", 0.2))

    print("[report_agent] Generating pipeline run report...")

    snap = _build_snapshot(bt, train_info, fund_result)

    try:
        report_md = _ask_gpt(snap, model, temperature)
        os.makedirs(REPORTS_DIR, exist_ok=True)
        date_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        report_path = os.path.join(REPORTS_DIR, f"run_{date_str}.md")
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_md)
        print(f"[report_agent] Report saved → {report_path}")
        _save_last_run(snap)
    except Exception as e:
        print(f"[report_agent] GPT call failed: {e}")
        _save_last_run(snap)
